### PR TITLE
Automationtrials

### PR DESCRIPTION
**Pull request by gitlost-murali**
Added another entry in `.json` for background color by entering the pixel location. We can get the color of the background from the location specified and later fill the color in the rectangle specified.

"T1": { "frames": [27], "box": [515, 275, 870, 460], "color": "black","bgloc":[500,200]},

Note: It is not mandatory to include `bgloc` in `.json` file if one wants to use `Paint/GIMP`.

### CODE REVIEW

**Comment by gitlost-murali** [comment]
Works with Image as input. Didn't do it for GIFs

**Comment by gitlost-murali** [comment]
Works fine with GIFs

**Comment by srmsoumya** [comment]
@gitlost-murali Is `bgloc`, the centroid of the box?

Few things to think about:
- If it is centroid of the box, should it be a property of the box
- Is the property required? If we have the bounding box, can we consider inferring the color from that.

**Comment by gitlost-murali** [comment]
`bgloc` is any location.

It doesn't have to the centroid. Let's say that the background-color is `blue` and Text written on it is `white`. We can't be sure about centroid being located on the text pixels or on the background pixels.

`bgloc` is an optional requirement. If people are comfortable using `Paint/GIMP`, they can skip `bgloc` in their JSON file.

**Comment by srmsoumya** [comment]
Yes, makes sense.

Probably creating another issue will help. Given a bounding box, compute the dominant pixel & color accordingly.

**Pull request merged**
